import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { HeaderComponent } from './header/header.component';
import { HomeComponent } from './home/home.component';
import { AsesoriasComponent } from './asesorias/asesorias.component';
import { EducacionComponent } from './educacion/educacion.component';
import { HerramientasComponent } from './herramientas/herramientas.component';
import { ContactComponent } from './contact/contact.component';
import { TarjetaDeCreditoComponent } from './educacion/tarjeta-de-credito/tarjeta-de-credito.component';
import { DisclaimerComponent } from './shared/disclaimer/disclaimer.component';
import { CalculadoraCuotasComponent } from './herramientas/calculadora-cuotas/calculadora-cuotas.component';
import { ReactiveFormsModule, FormsModule } from '@angular/forms';
import { DiccionarioFinancieroComponent } from './educacion/diccionario-financiero/diccionario-financiero.component';
import { PlanillaGastosComponent } from './herramientas/planilla-gastos/planilla-gastos.component';
import { OrdenFinancieroComponent } from './educacion/orden-financiero/orden-financiero.component';
import { DeudaComponent } from './educacion/deuda/deuda.component';

// ✅ Lucide Angular
import {
  ArrowBigRight,
  BarChart,
  Calendar,
  LucideAngularModule,
  Recycle,
  ScrollTextIcon,
  ShieldQuestion,
} from 'lucide-angular';
import {
  CreditCard,
  Wallet,
  PiggyBank,
  Banknote,
  Coins,
  TrendingUp,
  TrendingDown,
  CalendarDays,
  BookOpenCheck,
  CircleCheck,
  AlertTriangle,
  Gift,
  ListChecks,
  Droplet,
  Home,
  User,
  Users,
  UserCheck,
  Info,
  ClipboardList,
  FileText,
  FileCheck2,
  Inbox,
  Folder,
  Layers,
  Briefcase,
  DollarSign,
  Landmark,
  Building2,
  BadgeCheck,
  Lock,
  Send,
  Save,
  Settings,
  Bell,
  HelpCircle,
  ThumbsUp,
  ThumbsDown,
  Search,
  LayoutDashboard,
  Wrench,
  ArrowBigRightIcon,
  ChartBar,
  ThumbsDownIcon,
  ScrollText,
  BookA,
  HandCoins,
  ChartLine,
  BanknoteArrowUp,
  RecycleIcon,
  TableOfContents,
  ChartNoAxesCombined,
  Lightbulb,
  ChevronRight,
  Hourglass,
  CircleDollarSign,
  BadgeCheckIcon,
  Brain,
  BadgeX,
  MousePointerClick,
  Calculator,
  Eye,
  SquarePen,
  Bitcoin,
  LandmarkIcon,
  Download,
  ChartPie,
  Utensils,
  AlertTriangleIcon,
  Smartphone,
  CalendarCheck,
  UserCheckIcon,
  SettingsIcon,
  Mail,
  Instagram,
  Github,
  FolderArchive,
} from 'lucide-angular';

@NgModule({
  declarations: [
    AppComponent,
    HeaderComponent,
    HomeComponent,
    AsesoriasComponent,
    EducacionComponent,
    HerramientasComponent,
    ContactComponent,
    TarjetaDeCreditoComponent,
    DisclaimerComponent,
    CalculadoraCuotasComponent,
    DiccionarioFinancieroComponent,
    PlanillaGastosComponent,
    OrdenFinancieroComponent,
    DeudaComponent,
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    ReactiveFormsModule,
    FormsModule,
    LucideAngularModule.pick({
      CreditCard,
      Wallet,
      PiggyBank,
      Banknote,
      Coins,
      TrendingUp,
      TrendingDown,
      CalendarDays,
      BookOpenCheck,
      CircleCheck,
      AlertTriangle,
      Gift,
      ListChecks,
      Droplet,
      Home,
      User,
      Users,
      UserCheck,
      Info,
      ClipboardList,
      FileText,
      FileCheck2,
      Inbox,
      Folder,
      Layers,
      Briefcase,
      DollarSign,
      Landmark,
      Building2,
      BadgeCheck,
      Lock,
      Send,
      Save,
      Settings,
      Bell,
      HelpCircle,
      ThumbsUp,
      ThumbsDown,
      Search,
      LayoutDashboard,
      Wrench,
      ArrowBigRightIcon,
      ChartBar,
      ThumbsDownIcon,
      ScrollText,
      BookA,
      HandCoins,
      ChartLine,
      BanknoteArrowUp,
      RecycleIcon,
      TableOfContents,
      ChartNoAxesCombined,
      Lightbulb,
      ChevronRight,
      Hourglass,
      CircleDollarSign,
      BadgeCheckIcon,
      Brain,
      BadgeX,
      MousePointerClick,
      Calculator,
      Eye,
      SquarePen,
      Bitcoin,
      LandmarkIcon,
      Download,
      ChartPie,
      Utensils,
      AlertTriangleIcon,
      Smartphone,
      CalendarCheck,
      ShieldQuestion,
      UserCheckIcon,
      SettingsIcon,
      Mail,
      Instagram,
      Github,
      FolderArchive,
    }),
  ],
  providers: [],
  bootstrap: [AppComponent],
})
export class AppModule {}
